default:
  input_profile:
    input_synid: syn7984097
    project_id: syn51769643
    network_method: ["wgcna"]
    na_fill: NULL
    p_val_c3net: 1
    p_val_mrnet: 1
    p_val_wgcna: 1
    temp_storage_loc: /home/rstudio/temp/
    rsquaredCut: 0.80
    defaultnaPower: 6
  provenance:
    annotations:
      data_type: ['clinical','geneExpression']
      resource_type: metadata
      metadata_type: 'analytical covariates'
      ismodelsystem: FALSE
      ismultispecimen: TRUE
      fileformat: csv
      grant: U01AG046152
      species: Human
      organ: brain
      tissue: ['dorsolateral prefrontal cortex', 'Head of caudate nucleus', 'posterior cingulate cortex']
      study: ["ROSMAP","rnaSeqReprocessing"]
      consortium: AMP-AD
      assay: rnaSeq
    code_annotations:
        repository: PradoVarathan/Reprocessing_Metnetwork_Analysis
        ref: branch
        ref_name: main
        repository_path: Network_Wrapper.R
    activity_name: wgcna_rosmap_network
    activity_description: 'Using wgcna to prepare network from syn7984097 ROSMAP data'
  output_profile:
    output_path: /home/rstudio/meta_out/
    md5_output_path: rosmap_wgcna_md5.out
    output_name: 'rosmap_wgcna_network'
    error_path: /home/rstudio/error/
  computing_specs:
    light_ncores: 8
    medium_ncores: 0
    heavy_ncores: 0

