#' This function wraps c3net implementation
#'
#' This function wraps the c3net call on a gene expression matrix. The input
#' matrix is assumed to have samples as rows and genes as columns, so this
#' function takes the transpose of the matrix to be in the proper orientation
#' for c3net.
#'
#' @param data Required. A Matrix containing gene expression values with samples
#' as row values and genes as column IDs.
#' @param outputpath Required. Path to save the resulting network
#' @param c3net_alpha Optional. The statistical significance threshold for c3net.
#' Default is 0.01, which is the default value for the c3net() function.
#' @param debug_save Optional. Whether to save the network matrix as an RDS
#' file, for debugging purposes.
#'
#' @return a vector of file names corresponding to the files generated by this
#' function. Currently the only file is: `outputpath`/c3netNetwork.csv.
#'
#' @references G. Altay, F. Emmert-Streib, "Inferring the conservative causal core of gene regulatory networks", BMC Systems Biology (2010) 4:132.
#'
#' @export
c3netWrapper <- function(data, outputpath, c3net_alpha = 0.01, debug_save = FALSE) {
  net_filename <- file.path(outputpath, "c3netNetwork.csv")

  network <- c3net::c3net(t(data), alpha = c3net_alpha)

  if (debug_save) {
    saveRDS(network, file = file.path(outputpath, "result_c3net.rds"))
  }

  data.table::fwrite(network * upper.tri(network),
                     file = net_filename,
                     sep = ",",
                     row.names = TRUE,
                     col.names = TRUE)

  return(c(net_filename))
}
