#' Implements mrnet
#'
#' This function infers the interaction network of `data` using the MRNET algorithm.
#' It also infers the network using ARACNE from the same package and returns both
#' networks.
#'
#' @param data Required. A gene expression matrix with rows as sample IDs and
#' columns as Gene or feature IDs. The matrix will be transposed to work with
#' mrnet.
#' @param outputpath Required. The output path to save the resulting coexpression
#' network
#' @param mrnet_k Optional. The number of clusters (k) to use with `knnmi.all`.
#' Default is 3, which is also the default for `knnmi.all`.
#' @param debug_save Optional. Whether to save the network matrix as an RDS
#' file, for debugging purposes.
#'
#' @return a vector of file names corresponding to the files generated by this
#' function. The files will be `<outputpath>/aracneNetwork.csv` and
#' `<outputpath>/mrnetNetwork.csv`
#'
#' @export
mrnetWrapper = function(data, outputpath, mrnet_k = 3, debug_save = FALSE) {
  mi <- parmigene::knnmi.all(t(data), k = mrnet_k)

  networks <- list(aracne = parmigene::aracne.m(mi),
                   mrnet = parmigene::mrnet(mi))

  if (debug_save) {
    saveRDS(mi, file = file.path(outputpath, "mrnet_knnmi.rds"))
    saveRDS(networks[["aracne"]], file = file.path(outputpath, "result_aracne.rds"))
    saveRDS(networks[["mrnet"]], file = file.path(outputpath, "result_mrnet.rds"))
  }

  net_filenames <- c(aracne = file.path(outputpath, "aracneNetwork.csv"),
                     mrnet = file.path(outputpath, "mrnetNetwork.csv"))

  for (net_type in names(networks)) {
    data.table::fwrite(networks[[net_type]] * upper.tri(networks[[net_type]]),
                       file = net_filenames[net_type],
                       sep = ",",
                       row.names = TRUE,
                       col.names = TRUE)
  }

  return(net_filenames)
}
