#' Implements mrnet
#'
#' This function infers the interaction network of `data` using the MRNET algorithm.
#'
#' @param data Required. A gene expression matrix with rows as sample IDs and
#' columns as Gene or feature IDs. The matrix will be transposed to work with
#' mrnet.
#' @param outputpath Required. The output path to save the resulting coexpression
#' network
#' @param mrnet_k Optional. The number of clusters (k) to use with `knnmi.all`.
#' Default is 3, which is also the default for `knnmi.all`.
#' @param debug_save Optional. Whether to save the network matrix as an RDS
#' file, for debugging purposes.
#'
#' @return a vector of file names corresponding to the files generated by this
#' function. Currently the only file is: `<outputpath>/mrnetNetwork.csv`
#'
#' @importFrom magrittr %>%
#' @export
mrnetWrapper = function(data, outputpath, mrnet_k = 3, debug_save = FALSE) {
  mi <- parmigene::knnmi.all(t(data), k = mrnet_k)
  network <- parmigene::mrnet(mi)

  if (debug_save) {
    saveRDS(mi, file = file.path(outputpath, "mrnet_knnmi.rds"))
    saveRDS(network, file = file.path(outputpath, "result_mrnet.rds"))
  }

  net_filename <- file.path(outputpath, "mrnetNetwork.csv")
  data.table::fwrite(network * upper.tri(network),
                     file = net_filename,
                     sep = ",",
                     row.names = TRUE,
                     col.names = TRUE)

  return(c(net_filename))
}
