#' Parallel Network Wrapper
#'
#' Wrapper to run network detection in a parallel fashion
#'
#' @param data Required. Expression matrix to be used for network construction,
#' which should have samples as rows and genes as columns.
#' @param n_cores Optional. The number of parallel cores to use.
#' @param cluster_type Optional. Use "FORK" if running on a Unix system, and
#' "PSOCK" if running on Windows.
#' @param regressionFunction Required. The name of the regression function to use,
#' which should exactly match the name of a function in this package. Current
#' options are: lassoAIC, lassoBIC, lassoCV1se, lassoCVmin, ridgeAIC, ridgeBIC,
#' ridgeCV1se, ridgeCVmin, sparrowZ, sparrow2Z
#' @param outputpath Required. The output path to save the resulting coexpression
#' network
#' @param eigen Required for ridgeAIC and ridgeBIC, ignored otherwise. Eigen
#' cutoff value.
#' @param regulatorIndex Optional. A vector of numerical indexes into
#' `colnames(data)` for a subset of genes that should be used in the network,
#' rather than using the full gene set.
#' @param debug_save Optional. Whether to save the network matrix as an RDS
#' file, for debugging purposes.
#'
#' @return a vector of file names corresponding to the files generated by this
#' function. Currently the only file is: `<outputpath>/<regressionFunction>Network.csv`
#'
#' @importFrom foreach %dopar%
#' @importFrom foreach foreach
#'
#' @export
parallelNetworkWrapper <- function(data, n_cores = 0, cluster_type = "FORK",
                                   regressionFunction, outputpath,
                                   eigen = NULL, regulatorIndex = NULL,
                                   debug_save = FALSE) {
  clust <- NULL
  if (n_cores > 1) {
    clust <- parallel::makeCluster(n_cores, type = cluster_type,
                                   outfile = file.path(outputpath,
                                                       paste0(regressionFunction, "_log.txt")))
    doParallel::registerDoParallel(clust)
  }

  n_genes <- ncol(data)

  if (regressionFunction == 'ridgeAIC' |
      regressionFunction == 'ridgeBIC') {
    eigen <- svd(data)$d^2
  }

  gene_number <- NULL # Necessary to pass R CMD check

  results <- foreach(gene_number = 1:n_genes) %dopar% {
    res <- NA

    set.seed(gene_number)

    fxnArgs <- list()
    fxnArgs$y <- data[, gene_number]
    fxnArgs$x <- data[, -gene_number]

    if (regressionFunction == 'sparrowZ' |
        regressionFunction == 'sparrow2Z' |
        regressionFunction == 'sparrow2ZFDR') {
      fxnArgs$n_orderings <- 12
    }

    if (!is.null(eigen)) {
      fxnArgs$eigen <- eigen
    }

    if (is.null(regulatorIndex)) {
      temp_vbsr <- rep(0, n_genes)

      try(res <- do.call(regressionFunction, fxnArgs), silent = TRUE)

      if (!is.na(res)) {
        temp_vbsr[-gene_number] <- res
      }
    } else {
      temp_vbsr <- rep(0, length(regulatorIndex))

      fxnArgs$x <- data[, regulatorIndex]

      if (gene_number %in% regulatorIndex) {
        wi <- which(regulatorIndex %in% gene_number)
        fxnArgs$x <- fxnArgs$x[, -wi]
      }

      try(res <- do.call(regressionFunction, fxnArgs), silent = TRUE)

      if (!is.na(res)) {
        if(gene_number %in% regulatorIndex) {
          temp_vbsr[-wi] <- res
        } else {
          temp_vbsr <- res
        }
      }
    }

    return(temp_vbsr)
  }

  if (!is.null(clust)) {
    parallel::stopCluster(clust)
  }

  network <- do.call(rbind, results)

  colnames(network) <- colnames(data)
  rownames(network) <- colnames(data)

  # JB TODO what does this code do?
  network <- t(network)
  gc()
  network <- data.frame(network)
  gc()
  network$fold <- as.integer(network$fold)
  network <- network[, -1]
  gc()
  network <- network / 2 + t(network) / 2

  if (debug_save) {
    saveRDS(network, file.path(outputpath,
                               paste0("result_", regressionFunction, ".rds")))
  }

  net_file <- file.path(outputpath, paste0(regressionFunction, "Network.csv"))

  data.table::fwrite(network * upper.tri(network),
                     file = net_file,
                     sep = ",",
                     row.names = TRUE,
                     col.names = TRUE)

  return(c(net_file))
}
