#' Runs WGCNA TOMsimilarity
#'
#' Runs WGCNA::TOMsimilarity over a gene expression matrix.
#'
#' @param data Required. A Matrix containing gene expression values with samples
#' as row values and genes as column IDs
#' @param outputpath Required. Path to save the resulting network
#' @param RsquaredCut Optional. Minimum R^2 value to use when picking a soft threshold.
#' Corresponds to the RsquaredCut argument in WGCNA::pickSoftThreshold.
#' @param defaultPower Optional. The default soft power to use if pickSoftThreshold
#' returns NA.
#' @param ncores Optional. How many cores/threads to allow when running WGCNA.
#' The default value of 0 means "do not thread".
#' @param debug_save Optional. Whether to save the TOM similarity matrix as an RDS
#' file before reducing it to an upper triangular matrix, for debugging purposes.
#'
#' @return a vector of file names corresponding to the files generated by this
#' function. This vector will have 3 file names: `outputpath`/wgcnaPowerEstimate.txt,
#' `outputpath`/wgcnaSoftThresholdNetwork.csv, and `outputpath`/wgcnaTopologicalOverlapMatrixNetwork.csv
#'
#' @export
wgcnaTOM <- function(data, outputpath, RsquaredCut = .85, defaultPower = 6,
                     ncores = 0, debug_save = FALSE) {
  # TODO we could make these configurable
  power_est_filename <- file.path(outputpath, "wgcnaPowerEstimate.txt")
  soft_thresh_filename <- file.path(outputpath, "wgcnaSoftThresholdNetwork.csv")
  topo_net_filename <- file.path(outputpath, "wgcnaTopologicalOverlapMatrixNetwork.csv")

  if (ncores > 0) {
    WGCNA::enableWGCNAThreads(nThreads = ncores)
  }

  res <- WGCNA::pickSoftThreshold(data, RsquaredCut = RsquaredCut)
  if (is.na(res$powerEstimate)) {
    res$powerEstimate <- defaultPower
  }

  cat(res$powerEstimate, "\n", sep = "", file = power_est_filename)
  message(paste("Power estimate:", res$powerEstimate, "for RsquaredCut =", RsquaredCut))

  network <- WGCNA::adjacency(data, power = res$powerEstimate)

  data.table::fwrite(network * upper.tri(network),
                     file = soft_thresh_filename,
                     sep = ",",
                     row.names = TRUE,
                     col.names = TRUE)

  cn <- colnames(network)
  network <- WGCNA::TOMsimilarity(network)
  colnames(network) <- cn
  rownames(network) <- cn

  if (debug_save) {
    saveRDS(network, file = file.path(outputpath, 'result_wgcnaTOM.rds'))
  }

  network <- network * upper.tri(network)
  data.table::fwrite(network,
                     file = topo_net_filename,
                     sep = ",",
                     row.names = TRUE,
                     col.names = TRUE)

  if (ncores > 0) {
    WGCNA::disableWGCNAThreads()
  }

  return(c(power_est_filename, soft_thresh_filename, topo_net_filename))
}
